import { useQuery } from '@tanstack/react-query';
import { Ban, CheckCheck, ClipboardCheck, Lock, RefreshCw, Wallet } from 'lucide-react';
import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ErrorState, Money, PageHeader } from '@/components/common';
import { Button } from '@/components/ui/button';
import { Alert, Card, CardHeader, Skeleton, Stat, StatusBadge } from '@/components/ui/display';
import { Field, Input } from '@/components/ui/form';
import { ConfirmDialog } from '@/components/ui/overlay';
import { api } from '@/lib/api';
import { useAuth } from '@/lib/auth';
import { useApiMutation } from '@/lib/mutation';
import { cn, formatCompact, formatDateTime } from '@/lib/utils';
import type { PayrollRun, PayrollStatus } from '@/types';
import { AdjustmentsDialog } from './AdjustmentsDialog';
import { RegisterTable } from './RegisterTable';

const STEPS: { status: PayrollStatus; label: string }[] = [
  { status: 'DRAFT', label: 'Draft' },
  { status: 'REVIEWED', label: 'Reviewed' },
  { status: 'APPROVED', label: 'Approved' },
  { status: 'PAID', label: 'Paid' },
];

type Action = 'recalculate' | 'review' | 'approve' | 'mark-paid' | 'cancel';
const ACTION_COPY: Record<Action, { title: string; body: string; label: string; tone: 'primary' | 'danger' }> = {
  recalculate: { title: 'Recalculate payroll?', body: 'Every employee is recalculated from current salaries, attendance, leave and adjustments. Review status is cleared.', label: 'Recalculate', tone: 'primary' },
  review: { title: 'Mark as reviewed?', body: 'Confirms the figures have been checked. An approver can then approve it.', label: 'Mark reviewed', tone: 'primary' },
  approve: { title: 'Approve payroll?', body: 'This locks the payroll so it cannot be changed, issues a payslip to every employee and notifies them.', label: 'Approve and issue payslips', tone: 'primary' },
  'mark-paid': { title: 'Mark as paid?', body: 'Record that salaries have been transferred. Paid payroll cannot be cancelled.', label: 'Mark paid', tone: 'primary' },
  cancel: { title: 'Cancel this payroll?', body: 'Payslips from this run are withdrawn and the month can be run again. Figures stay in history.', label: 'Cancel payroll', tone: 'danger' },
};

export default function PayrollRunPage() {
  const { id } = useParams();
  const { can } = useAuth();
  const { data: p, isLoading, error, refetch } = useQuery({ queryKey: ['payroll-run', id], queryFn: () => api.get<PayrollRun>(`/payroll/${id}`) });
  const [action, setAction] = useState<Action | null>(null);
  const [reason, setReason] = useState('');
  const [adjOpen, setAdjOpen] = useState(false);

  const run = useApiMutation((a: Action) => api.post<PayrollRun>(`/payroll/${id}/${a}`, a === 'cancel' ? { reason } : {}), {
    success: (r) => `Payroll is now ${r.data.status.toLowerCase()}`,
    invalidate: [['payroll-run', id], ['payroll'], ['register', id], ['dashboard'], ['payslips']],
    onSuccess: () => {
      setAction(null);
      setReason('');
    },
  });

  if (error) return <ErrorState error={error} retry={() => refetch()} />;
  if (isLoading || !p) return <Skeleton className="h-96" />;

  const stepIndex = STEPS.findIndex((s) => s.status === p.status);
  const actions: { key: Action; label: string; icon: React.ReactNode; show: boolean; variant?: 'secondary' | 'primary' | 'ghost' }[] = [
    { key: 'recalculate', label: 'Recalculate', icon: <RefreshCw />, show: can('payroll.process') && ['DRAFT', 'REVIEWED'].includes(p.status), variant: 'secondary' },
    { key: 'review', label: 'Mark reviewed', icon: <ClipboardCheck />, show: can('payroll.process') && p.status === 'DRAFT' },
    { key: 'approve', label: 'Approve', icon: <CheckCheck />, show: can('payroll.approve') && p.status === 'REVIEWED' },
    { key: 'mark-paid', label: 'Mark paid', icon: <Wallet />, show: can('payroll.approve') && p.status === 'APPROVED' },
    { key: 'cancel', label: 'Cancel', icon: <Ban />, show: can('payroll.approve') && ['DRAFT', 'REVIEWED', 'APPROVED'].includes(p.status), variant: 'ghost' },
  ];

  return (
    <div className="space-y-5">
      <PageHeader
        title={`Payroll · ${p.period}`}
        breadcrumb={<Link to="/app/payroll/runs" className="hover:text-fg">Payroll</Link>}
        description={
          <span className="flex flex-wrap items-center gap-2">
            <StatusBadge status={p.status} />
            {p.locked && (
              <span className="inline-flex items-center gap-1 text-xs">
                <Lock className="size-3" /> Locked
              </span>
            )}
            <span className="text-xs">
              Generated by {p.generatedBy ?? '—'} · {formatDateTime(p.createdAt)}
              {p.approvedBy && ` · Approved by ${p.approvedBy}`}
            </span>
          </span>
        }
        actions={
          <>
            {can('payroll.process') && (
              <Button variant="secondary" onClick={() => setAdjOpen(true)}>
                Adjustments
              </Button>
            )}
            {actions
              .filter((a) => a.show)
              .map((a) => (
                <Button key={a.key} variant={a.variant ?? 'primary'} onClick={() => setAction(a.key)}>
                  {a.icon} {a.label}
                </Button>
              ))}
          </>
        }
      />

      {p.status !== 'CANCELLED' && (
        <ol className="flex items-center gap-2 overflow-x-auto text-sm" aria-label="Payroll progress">
          {STEPS.map((s, i) => (
            <li key={s.status} className="flex shrink-0 items-center gap-2">
              <span className={cn('flex size-6 items-center justify-center rounded-full text-xs font-semibold', i <= stepIndex ? 'bg-primary text-primary-fg' : 'bg-surface-2 text-subtle')}>{i + 1}</span>
              <span className={i <= stepIndex ? 'font-medium text-fg' : 'text-subtle'}>{s.label}</span>
              {i < STEPS.length - 1 && <span className={cn('h-px w-8 sm:w-16', i < stepIndex ? 'bg-primary' : 'bg-border')} aria-hidden />}
            </li>
          ))}
        </ol>
      )}

      {p.status === 'CANCELLED' && <Alert tone="neutral" title="This payroll was cancelled">{p.notes}</Alert>}
      {p.disclaimer && <Alert tone="amber">{p.disclaimer}</Alert>}

      <div className="grid grid-cols-2 gap-3 lg:grid-cols-5">
        <Stat label="Employees" value={p.employeeCount} />
        <Stat label="Working days" value={p.workingDays} tone="blue" />
        <Stat label="Gross" value={`NPR ${formatCompact(p.totalGross)}`} tone="blue" hint={<Money value={p.totalGross} />} />
        <Stat label="Tax" value={`NPR ${formatCompact(p.totalTax)}`} tone="amber" hint={<Money value={p.totalTax} />} />
        <Stat label="Net pay" value={`NPR ${formatCompact(p.totalNet)}`} tone="green" hint={<Money value={p.totalNet} />} />
      </div>

      {p.byDepartment && p.byDepartment.length > 0 && (
        <Card>
          <CardHeader title="By department" />
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead className="bg-surface-2/60 text-xs uppercase tracking-wide text-subtle">
                <tr>
                  <th className="px-4 py-2 text-left font-semibold">Department</th>
                  <th className="px-4 py-2 text-right font-semibold">Employees</th>
                  <th className="px-4 py-2 text-right font-semibold">Gross</th>
                  <th className="px-4 py-2 text-right font-semibold">Tax</th>
                  <th className="px-4 py-2 text-right font-semibold">Net</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {p.byDepartment.map((d) => (
                  <tr key={d.department}>
                    <td className="px-4 py-2 text-fg">{d.department}</td>
                    <td className="num px-4 py-2 text-right">{d.employees}</td>
                    <td className="px-4 py-2 text-right"><Money value={d.gross} /></td>
                    <td className="px-4 py-2 text-right"><Money value={d.tax} /></td>
                    <td className="px-4 py-2 text-right"><Money value={d.net} /></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>
      )}

      <RegisterTable payrollId={p.id} />

      {action && (
        <ConfirmDialog
          open
          onOpenChange={(o) => !o && setAction(null)}
          title={ACTION_COPY[action].title}
          description={ACTION_COPY[action].body}
          confirmLabel={ACTION_COPY[action].label}
          tone={ACTION_COPY[action].tone}
          loading={run.isPending}
          onConfirm={() => (action === 'cancel' && reason.trim().length < 3 ? undefined : run.mutate(action))}
        >
          {action === 'cancel' && (
            <Field label="Reason" required>
              {(pp) => <Input {...pp} value={reason} onChange={(e) => setReason(e.target.value)} placeholder="e.g. Wrong attendance for Operations" />}
            </Field>
          )}
        </ConfirmDialog>
      )}
      {adjOpen && <AdjustmentsDialog open={adjOpen} onOpenChange={setAdjOpen} year={p.year} month={p.month} locked={p.locked || p.status === 'CANCELLED'} />}
    </div>
  );
}
