/**
 * Development seed for Sprasa HR.
 *
 * Creates "Sprasa Demo Organisation" with departments, ~40 fictional employees, shifts,
 * holidays, three months of attendance, leave in every state, and payroll runs produced by the
 * real payroll service. Every person here is fictional.
 *
 *   npm run db:seed                 # refuses to run if data exists
 *   SEED_RESET=true npm run db:seed # wipes all tables first (development only!)
 *
 * Demo login password: value of SEED_PASSWORD, default "Sprasa@2026". Change it after first login.
 */
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { Prisma } from '@prisma/client';
import PDFDocument from 'pdfkit';
import { env } from '../backend/src/config/env';
import { prisma } from '../backend/src/lib/prisma';
import { hashPassword } from '../backend/src/modules/auth/auth.service';
import * as payroll from '../backend/src/modules/payroll/payroll.service';
import * as leave from '../backend/src/modules/leave/leave.service';
import { computeAttendance } from '../backend/src/services/engines/attendance.engine';
import { dayKind } from '../backend/src/services/engines/calendar.engine';
import { loadWorkCalendar } from '../backend/src/services/calendar.service';
import { bootstrapOrganisation } from '../backend/src/services/org-bootstrap.service';
import { ensureLeaveBalances } from '../backend/src/services/leave-balance.service';
import { toShiftRule } from '../backend/src/services/shift-resolver.service';
import type { AuthContext } from '../backend/src/types/express';
import { addDays, eachDay, formatDateOnly, parseDateOnly, todayIn } from '../backend/src/utils/dates';

const PASSWORD = process.env.SEED_PASSWORD || 'Sprasa@2026';

// Deterministic pseudo-random numbers so every seed produces the same demo.
let seedState = 20260930;
function rand() {
  seedState |= 0;
  seedState = (seedState + 0x6d2b79f5) | 0;
  let t = Math.imul(seedState ^ (seedState >>> 15), 1 | seedState);
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
}
const pick = <T>(list: readonly T[]) => list[Math.floor(rand() * list.length)];
const between = (min: number, max: number) => Math.floor(rand() * (max - min + 1)) + min;
const hhmm = (minutes: number) => `${String(Math.floor(minutes / 60)).padStart(2, '0')}:${String(minutes % 60).padStart(2, '0')}`;

async function resetDatabase() {
  const tables = await prisma.$queryRaw<{ tablename: string }[]>`SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND tablename <> '_prisma_migrations'`;
  if (tables.length) await prisma.$executeRawUnsafe(`TRUNCATE ${tables.map((t) => `"${t.tablename}"`).join(', ')} RESTART IDENTITY CASCADE`);
}

function demoPdf(file: string, title: string, employee: string) {
  return new Promise<number>((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 60 });
    const out = fs.createWriteStream(file);
    doc.pipe(out);
    doc.fontSize(20).text(title).moveDown().fontSize(12).text(`Employee: ${employee}`).moveDown().fillColor('#64748B').text('Demo document generated by the Sprasa HR seed. Not a real record.');
    doc.end();
    out.on('finish', () => resolve(fs.statSync(file).size));
    out.on('error', reject);
  });
}

// Fictional names built from common Nepali given names and surnames.
const MALE = ['Aarav', 'Bibek', 'Dipesh', 'Ganesh', 'Kiran', 'Manish', 'Nabin', 'Prakash', 'Rajan', 'Sagar', 'Sanjay', 'Suman', 'Ujjwal', 'Bishal', 'Roshan', 'Anish', 'Pawan', 'Nirajan'];
const FEMALE = ['Anjali', 'Bina', 'Deepa', 'Gita', 'Kabita', 'Laxmi', 'Manisha', 'Nisha', 'Pooja', 'Rekha', 'Sabina', 'Sarita', 'Sunita', 'Srijana', 'Asmita', 'Pratiksha', 'Rojina', 'Kritika'];
const SURNAMES = ['Adhikari', 'Bhandari', 'Dahal', 'Gurung', 'KC', 'Karki', 'Khadka', 'Maharjan', 'Poudel', 'Rai', 'Shrestha', 'Tamang', 'Thapa', 'Basnet', 'Pandey', 'Rijal', 'Lama', 'Bhattarai', 'Joshi', 'Magar'];
const BANKS = ['Nabil Bank', 'NIC Asia Bank', 'Global IME Bank', 'Himalayan Bank', 'Nepal Investment Mega Bank', 'Everest Bank'];
const PLACES = [
  { district: 'Kathmandu', municipality: 'Kathmandu Metropolitan City', province: 'Bagmati', area: ['Baneshwor', 'Koteshwor', 'Kalanki', 'Maharajgunj', 'Chabahil'] },
  { district: 'Lalitpur', municipality: 'Lalitpur Metropolitan City', province: 'Bagmati', area: ['Jawalakhel', 'Kupondole', 'Satdobato', 'Imadol'] },
  { district: 'Bhaktapur', municipality: 'Madhyapur Thimi Municipality', province: 'Bagmati', area: ['Thimi', 'Sallaghari', 'Lokanthali'] },
];

async function main() {
  const existing = await prisma.organisation.count();
  if (existing > 0) {
    if (process.env.SEED_RESET !== 'true') {
      console.log('Database already has data. Run with SEED_RESET=true to wipe it and reseed (development only).');
      return;
    }
    if (env.isProduction) throw new Error('Refusing to reset a production database');
    console.log('Resetting database…');
    await resetDatabase();
  }

  const today = todayIn();
  console.log(`Seeding demo data (today = ${formatDateOnly(today)})…`);

  // ── Organisation ───────────────────────────────────────────
  const org = await prisma.organisation.create({
    data: {
      name: 'Sprasa Demo Organisation',
      legalName: 'Sprasa Demo Organisation Pvt. Ltd.',
      registrationNumber: '123456/079/080',
      panNumber: '609876543',
      address: 'New Baneshwor',
      province: 'Bagmati',
      district: 'Kathmandu',
      municipality: 'Kathmandu Metropolitan City',
      phone: '01-4000000',
      email: 'hr@example.com',
      website: 'https://sprasatechnicalsolution.com.np',
      fiscalYear: '2083/84',
      fiscalYearStart: parseDateOnly('2026-07-17'),
    },
  });
  const { roles } = await bootstrapOrganisation(prisma, org.id);
  const orgId = org.id;

  // Extra shifts
  const general = await prisma.shift.findFirstOrThrow({ where: { organisationId: orgId, name: 'General Shift' } });
  const morning = await prisma.shift.create({ data: { organisationId: orgId, name: 'Morning Shift', startTime: '07:00', endTime: '15:00', gracePeriod: 10, breakDuration: 45, workingHours: new Prisma.Decimal(7.25) } });
  await prisma.shift.create({ data: { organisationId: orgId, name: 'Flexible (8 hours)', startTime: '08:00', endTime: '18:00', gracePeriod: 0, breakDuration: 60, workingHours: new Prisma.Decimal(8), isFlexible: true } });

  // ── Departments & designations ─────────────────────────────
  const deptDefs = [
    ['Administration', 'ADM', 'Leadership, office administration and front desk'],
    ['Finance', 'FIN', 'Accounts, payroll and statutory filings'],
    ['Human Resources', 'HR', 'Recruitment, employee relations and HR operations'],
    ['Information Technology', 'IT', 'Software, infrastructure and support'],
    ['Operations', 'OPS', 'Field operations and service delivery'],
    ['Marketing', 'MKT', 'Brand, campaigns and customer outreach'],
  ] as const;
  const depts: Record<string, string> = {};
  for (const [name, code, description] of deptDefs) {
    const d = await prisma.department.create({ data: { organisationId: orgId, name, code, description } });
    depts[code] = d.id;
  }
  const desigDefs: [string, string, number][] = [
    ['Managing Director', 'ADM', 1],
    ['Admin Officer', 'ADM', 4],
    ['Office Assistant', 'ADM', 6],
    ['Finance Manager', 'FIN', 2],
    ['Accountant', 'FIN', 4],
    ['HR Manager', 'HR', 2],
    ['HR Officer', 'HR', 4],
    ['IT Manager', 'IT', 2],
    ['Senior Software Engineer', 'IT', 3],
    ['Software Engineer', 'IT', 4],
    ['IT Support Technician', 'IT', 5],
    ['Operations Manager', 'OPS', 2],
    ['Supervisor', 'OPS', 3],
    ['Field Technician', 'OPS', 5],
    ['Marketing Manager', 'MKT', 2],
    ['Marketing Executive', 'MKT', 4],
  ];
  const desig: Record<string, string> = {};
  for (const [name, dept, level] of desigDefs) {
    const d = await prisma.designation.create({ data: { organisationId: orgId, name, departmentId: depts[dept], level } });
    desig[name] = d.id;
  }

  // ── Salary structures ─────────────────────────────────────
  const comp = Object.fromEntries((await prisma.salaryComponent.findMany({ where: { organisationId: orgId } })).map((c) => [c.code, c]));
  const ssfStructure = await prisma.salaryStructure.create({
    data: {
      organisationId: orgId,
      name: 'Standard staff (SSF)',
      description: 'Housing 10% of basic, transport and food allowances, SSF employee contribution 11%.',
      lines: {
        create: [
          { componentId: comp.HOUSING.id, calculationType: 'PERCENT_OF_BASIC', value: new Prisma.Decimal(10) },
          { componentId: comp.TRANSPORT.id, calculationType: 'FIXED', value: new Prisma.Decimal(3000) },
          { componentId: comp.FOOD.id, calculationType: 'FIXED', value: new Prisma.Decimal(2500) },
          { componentId: comp.SSF.id, calculationType: 'PERCENT_OF_BASIC', value: new Prisma.Decimal(11) },
        ],
      },
    },
  });
  const pfStructure = await prisma.salaryStructure.create({
    data: {
      organisationId: orgId,
      name: 'Contract staff (PF)',
      description: 'Transport allowance with provident fund at 10% of basic.',
      lines: {
        create: [
          { componentId: comp.TRANSPORT.id, calculationType: 'FIXED', value: new Prisma.Decimal(2000) },
          { componentId: comp.PF.id, calculationType: 'PERCENT_OF_BASIC', value: new Prisma.Decimal(10) },
        ],
      },
    },
  });
  const structureLines = async (structureId: string) =>
    (await prisma.salaryStructureLine.findMany({ where: { structureId } })).map((l) => ({ componentId: l.componentId, calculationType: l.calculationType, value: l.value }));
  const ssfLines = await structureLines(ssfStructure.id);
  const pfLines = await structureLines(pfStructure.id);

  // ── Employees ──────────────────────────────────────────────
  type Spec = { code: string; designation: string; dept: string; basic: number; manager?: string; first?: string; last?: string; gender?: 'MALE' | 'FEMALE'; joined?: string; type?: 'FULL_TIME' | 'CONTRACT' | 'INTERN' | 'PART_TIME'; status?: 'ACTIVE' | 'PROBATION' | 'RESIGNED'; shift?: string };
  const specs: Spec[] = [
    { code: 'EMP-0001', designation: 'Managing Director', dept: 'ADM', basic: 220000, first: 'Rajendra', last: 'Shrestha', gender: 'MALE', joined: '2018-01-15' },
    { code: 'EMP-0002', designation: 'HR Manager', dept: 'HR', basic: 120000, manager: 'EMP-0001', first: 'Sunita', last: 'Adhikari', gender: 'FEMALE', joined: '2019-03-01' },
    { code: 'EMP-0003', designation: 'Finance Manager', dept: 'FIN', basic: 130000, manager: 'EMP-0001', joined: '2019-06-10' },
    { code: 'EMP-0004', designation: 'IT Manager', dept: 'IT', basic: 140000, manager: 'EMP-0001', first: 'Bibek', last: 'Karki', gender: 'MALE', joined: '2020-02-01' },
    { code: 'EMP-0005', designation: 'Operations Manager', dept: 'OPS', basic: 115000, manager: 'EMP-0001', joined: '2020-08-17' },
    { code: 'EMP-0006', designation: 'Marketing Manager', dept: 'MKT', basic: 110000, manager: 'EMP-0001', joined: '2021-01-04' },
    { code: 'EMP-0007', designation: 'Accountant', dept: 'FIN', basic: 62000, manager: 'EMP-0003', first: 'Kabita', last: 'Poudel', gender: 'FEMALE', joined: '2021-04-12' },
    { code: 'EMP-0008', designation: 'HR Officer', dept: 'HR', basic: 55000, manager: 'EMP-0002', joined: '2022-05-02' },
    { code: 'EMP-0009', designation: 'Software Engineer', dept: 'IT', basic: 75000, manager: 'EMP-0004', first: 'Anish', last: 'Thapa', gender: 'MALE', joined: '2022-09-19' },
  ];
  const fill: [string, string, number, number, string][] = [
    ['Admin Officer', 'ADM', 1, 48000, 'EMP-0001'],
    ['Office Assistant', 'ADM', 2, 26000, 'EMP-0001'],
    ['Accountant', 'FIN', 2, 58000, 'EMP-0003'],
    ['HR Officer', 'HR', 1, 52000, 'EMP-0002'],
    ['Senior Software Engineer', 'IT', 2, 105000, 'EMP-0004'],
    ['Software Engineer', 'IT', 5, 70000, 'EMP-0004'],
    ['IT Support Technician', 'IT', 2, 38000, 'EMP-0004'],
    ['Supervisor', 'OPS', 2, 50000, 'EMP-0005'],
    ['Field Technician', 'OPS', 7, 32000, 'EMP-0005'],
    ['Marketing Executive', 'MKT', 4, 45000, 'EMP-0006'],
  ];
  let n = specs.length;
  for (const [designation, dept, count, basic, manager] of fill) {
    for (let i = 0; i < count; i++) {
      n++;
      const year = between(2021, 2026);
      const month = year === 2026 ? between(1, 8) : between(1, 12);
      specs.push({
        code: `EMP-${String(n).padStart(4, '0')}`,
        designation,
        dept,
        basic: basic + between(-4, 8) * 1000,
        manager,
        joined: `${year}-${String(month).padStart(2, '0')}-${String(between(1, 25)).padStart(2, '0')}`,
        type: designation === 'Field Technician' && i > 4 ? 'CONTRACT' : designation === 'Software Engineer' && i === 4 ? 'INTERN' : 'FULL_TIME',
        status: year === 2026 && month >= 5 ? 'PROBATION' : 'ACTIVE',
        shift: dept === 'OPS' ? morning.id : undefined,
      });
    }
  }
  // Two leavers for the turnover and exit reports.
  specs.push({ code: `EMP-${String(++n).padStart(4, '0')}`, designation: 'Marketing Executive', dept: 'MKT', basic: 42000, manager: 'EMP-0006', joined: '2022-02-01', status: 'RESIGNED' });
  specs.push({ code: `EMP-${String(++n).padStart(4, '0')}`, designation: 'Field Technician', dept: 'OPS', basic: 30000, manager: 'EMP-0005', joined: '2023-07-01', status: 'RESIGNED' });

  const idByCode: Record<string, string> = {};
  const usedNames = new Set<string>();
  const passwordHash = await hashPassword(PASSWORD);
  const exitDates = [addDays(today, -40), addDays(today, -95)];
  let exitIdx = 0;

  for (const s of specs) {
    const gender = s.gender ?? (rand() < 0.5 ? 'MALE' : 'FEMALE');
    let first = s.first;
    let last = s.last;
    while (!first || !last || usedNames.has(`${first} ${last}`)) {
      first = pick(gender === 'MALE' ? MALE : FEMALE);
      last = pick(SURNAMES);
    }
    usedNames.add(`${first} ${last}`);
    const place = pick(PLACES);
    const joinDate = parseDateOnly(s.joined!);
    const exited = s.status === 'RESIGNED';
    const exitDate = exited ? exitDates[exitIdx++] : null;
    const contract = s.type === 'CONTRACT';

    const emp = await prisma.employee.create({
      data: {
        organisationId: orgId,
        employeeCode: s.code,
        firstName: first,
        lastName: last,
        gender,
        maritalStatus: rand() < 0.55 ? 'MARRIED' : 'SINGLE',
        dateOfBirth: parseDateOnly(`${between(1975, 2001)}-${String(between(1, 12)).padStart(2, '0')}-${String(between(1, 28)).padStart(2, '0')}`),
        phone: `98${between(10000000, 69999999)}`,
        email: `${first.toLowerCase()}.${last.toLowerCase()}@example.com`,
        address: pick(place.area),
        province: place.province,
        district: place.district,
        municipality: place.municipality,
        emergencyContactName: `${pick(rand() < 0.5 ? MALE : FEMALE)} ${last}`,
        emergencyContactPhone: `98${between(10000000, 69999999)}`,
        citizenshipNumber: `${between(10, 75)}-01-${between(70, 79)}-${String(between(1, 99999)).padStart(5, '0')}`,
        panNumber: String(between(100000000, 999999999)),
        joinDate,
        exitDate,
        employmentType: s.type ?? 'FULL_TIME',
        status: s.status ?? 'ACTIVE',
        departmentId: depts[s.dept],
        designationId: desig[s.designation],
        managerId: s.manager ? idByCode[s.manager] : null,
        branch: 'Head Office',
        workLocation: s.dept === 'OPS' ? 'Field' : 'Kathmandu office',
        bankName: pick(BANKS),
        bankAccountNumber: String(between(10000000, 99999999)) + String(between(10000, 99999)),
        ssfNumber: contract ? null : String(between(1000000000, 9999999999)),
        pfNumber: contract ? String(between(100000, 999999)) : null,
        taxCategory: rand() < 0.4 ? 'COUPLE' : 'INDIVIDUAL',
      },
    });
    idByCode[s.code] = emp.id;

    await prisma.employmentHistory.create({ data: { employeeId: emp.id, eventType: 'JOINED', effectiveDate: joinDate, departmentId: emp.departmentId, designationId: emp.designationId, status: 'PROBATION', remarks: 'Joined the organisation' } });
    if ((s.status ?? 'ACTIVE') === 'ACTIVE' && joinDate < addDays(today, -180)) {
      await prisma.employmentHistory.create({ data: { employeeId: emp.id, eventType: 'STATUS_CHANGE', effectiveDate: addDays(joinDate, 180), departmentId: emp.departmentId, designationId: emp.designationId, status: 'ACTIVE', remarks: 'Confirmed after probation' } });
    }
    if (exited && exitDate) {
      await prisma.employmentHistory.create({ data: { employeeId: emp.id, eventType: 'EXIT', effectiveDate: exitDate, departmentId: emp.departmentId, designationId: emp.designationId, status: 'RESIGNED', remarks: 'Resigned for higher studies' } });
    }

    // Salary history: an older salary, then an annual increment from the start of this fiscal year.
    const lines = contract ? pfLines : ssfLines;
    const structureId = contract ? pfStructure.id : ssfStructure.id;
    const incrementDate = parseDateOnly('2026-07-17');
    if (joinDate < incrementDate && !exited) {
      await prisma.employeeSalary.create({ data: { employeeId: emp.id, structureId, basicSalary: new Prisma.Decimal(Math.round(s.basic * 0.92)), effectiveFrom: joinDate, effectiveTo: addDays(incrementDate, -1), reason: 'Initial salary', lines: { create: lines } } });
      await prisma.employeeSalary.create({ data: { employeeId: emp.id, structureId, basicSalary: new Prisma.Decimal(s.basic), effectiveFrom: incrementDate, reason: 'Annual increment FY 2083/84', lines: { create: lines } } });
      await prisma.employmentHistory.create({ data: { employeeId: emp.id, eventType: 'SALARY_CHANGE', effectiveDate: incrementDate, departmentId: emp.departmentId, designationId: emp.designationId, status: emp.status, remarks: 'Annual increment FY 2083/84' } });
    } else {
      await prisma.employeeSalary.create({ data: { employeeId: emp.id, structureId, basicSalary: new Prisma.Decimal(s.basic), effectiveFrom: joinDate, reason: 'Initial salary', lines: { create: lines } } });
    }

    await prisma.employeeShift.create({ data: { employeeId: emp.id, shiftId: s.shift ?? general.id, effectiveFrom: joinDate } });
    await ensureLeaveBalances(prisma, orgId, emp.id, today.getUTCFullYear());
  }

  // Department heads
  const heads: Record<string, string> = { ADM: 'EMP-0001', HR: 'EMP-0002', FIN: 'EMP-0003', IT: 'EMP-0004', OPS: 'EMP-0005', MKT: 'EMP-0006' };
  for (const [code, emp] of Object.entries(heads)) await prisma.department.update({ where: { id: depts[code] }, data: { headId: idByCode[emp] } });

  // ── Users ──────────────────────────────────────────────────
  const userDefs = [
    { username: 'superadmin', name: 'Rajendra Shrestha', email: 'superadmin@example.com', role: 'super_admin', employee: 'EMP-0001' },
    { username: 'hradmin', name: 'Sunita Adhikari', email: 'hradmin@example.com', role: 'hr_admin', employee: 'EMP-0002' },
    { username: 'manager', name: 'Bibek Karki', email: 'manager@example.com', role: 'manager', employee: 'EMP-0004' },
    { username: 'accountant', name: 'Kabita Poudel', email: 'accountant@example.com', role: 'accountant', employee: 'EMP-0007' },
    { username: 'employee', name: 'Anish Thapa', email: 'employee@example.com', role: 'employee', employee: 'EMP-0009' },
  ];
  const userIds: Record<string, string> = {};
  for (const u of userDefs) {
    const user = await prisma.user.create({
      data: { organisationId: orgId, username: u.username, name: u.name, email: u.email, passwordHash, roleId: roles[u.role], employeeId: idByCode[u.employee], emailVerifiedAt: new Date(), passwordChangedAt: new Date(Date.now() - 60_000) },
    });
    userIds[u.username] = user.id;
  }

  // ── Holidays (demo dates — confirm against the official calendar) ──
  const holidays: [string, string, 'PUBLIC' | 'ORGANISATION' | 'OPTIONAL'][] = [
    ['2026-01-15', 'Maghe Sankranti', 'PUBLIC'],
    ['2026-02-15', 'Maha Shivaratri', 'PUBLIC'],
    ['2026-03-03', 'Fagu Purnima (Holi)', 'PUBLIC'],
    ['2026-04-14', 'Nepali New Year 2083', 'PUBLIC'],
    ['2026-05-01', 'Labour Day', 'PUBLIC'],
    ['2026-05-28', 'Republic Day', 'PUBLIC'],
    ['2026-08-28', 'Janai Purnima', 'PUBLIC'],
    ['2026-09-19', 'Constitution Day', 'PUBLIC'],
    ['2026-10-17', 'Ghatasthapana', 'PUBLIC'],
    ['2026-10-23', 'Fulpati', 'PUBLIC'],
    ['2026-10-24', 'Maha Ashtami', 'PUBLIC'],
    ['2026-10-26', 'Vijaya Dashami', 'PUBLIC'],
    ['2026-10-27', 'Ekadashi', 'PUBLIC'],
    ['2026-11-08', 'Laxmi Puja', 'PUBLIC'],
    ['2026-11-10', 'Bhai Tika', 'PUBLIC'],
    ['2026-11-14', 'Chhath Parva', 'OPTIONAL'],
    ['2026-12-25', 'Christmas Day', 'OPTIONAL'],
    ['2026-06-15', 'Sprasa Foundation Day', 'ORGANISATION'],
  ];
  for (const [date, name, type] of holidays) {
    await prisma.holiday.create({ data: { organisationId: orgId, date: parseDateOnly(date), name, type, description: 'Demo date. Confirm against the official government calendar.' } });
  }

  // ── Leave requests (through the real service so balances stay consistent) ──
  const hrAuth: AuthContext = {
    userId: userIds.hradmin,
    organisationId: orgId,
    homeOrganisationId: orgId,
    roleKey: 'hr_admin',
    dataScope: 'ORGANISATION',
    permissions: new Set((await prisma.rolePermission.findMany({ where: { roleId: roles.hr_admin }, include: { permission: true } })).map((p) => p.permission.key)),
    employeeId: idByCode['EMP-0002'],
    name: 'Sunita Adhikari',
    email: 'hradmin@example.com',
  };
  const actor = { organisationId: orgId, userId: userIds.hradmin, ipAddress: '127.0.0.1', userAgent: 'seed' };
  const types = Object.fromEntries((await prisma.leaveType.findMany({ where: { organisationId: orgId } })).map((t) => [t.code, t]));
  const cal = await loadWorkCalendar(orgId, addDays(today, -120), addDays(today, 60));
  const nextWorking = (d: Date) => {
    let x = d;
    while (dayKind(x, cal) !== 'WORKING') x = addDays(x, 1);
    return x;
  };

  const activeCodes = specs.filter((s) => s.status !== 'RESIGNED' && s.code !== 'EMP-0002').map((s) => s.code);
  const leavePlans: { code: string; type: string; offset: number; days: number; outcome: 'APPROVED' | 'PENDING' | 'REJECTED' | 'SUPERVISOR' | 'CANCELLED'; reason: string }[] = [];
  const reasons: Record<string, string[]> = {
    AL: ['Family trip to Pokhara', 'Visiting home town for a family function', 'Personal time off', 'Attending a wedding in Chitwan'],
    SL: ['Fever and cold', 'Doctor appointment and rest', 'Recovering from food poisoning'],
    CL: ['Bank and land office work', 'Personal errand', 'Child’s school parent meeting'],
    UL: ['Extended personal travel'],
  };
  for (let i = 0; i < 26; i++) {
    const type = pick(['AL', 'AL', 'SL', 'SL', 'CL', 'CL', 'UL'] as const);
    const past = i < 17;
    leavePlans.push({
      code: pick(activeCodes),
      type,
      offset: past ? -between(5, 100) : between(3, 40),
      days: type === 'AL' ? between(2, 4) : type === 'UL' ? 2 : 1,
      outcome: past ? (i % 7 === 0 ? 'REJECTED' : i % 11 === 0 ? 'CANCELLED' : 'APPROVED') : i % 3 === 0 ? 'SUPERVISOR' : 'PENDING',
      reason: pick(reasons[type]),
    });
  }
  // A few people on leave today for the dashboard.
  for (const code of ['EMP-0012', 'EMP-0021', 'EMP-0030']) leavePlans.push({ code, type: 'AL', offset: -1, days: 3, outcome: 'APPROVED', reason: 'Family function' });
  // Pending requests for the demo manager's team so the manager login has something to approve.
  leavePlans.push({ code: 'EMP-0009', type: 'CL', offset: 6, days: 1, outcome: 'PENDING', reason: 'Personal errand' });

  const managerAuth = async (employeeCode: string): Promise<AuthContext | null> => {
    const emp = await prisma.employee.findUnique({ where: { id: idByCode[employeeCode] }, select: { managerId: true } });
    const managerUser = emp?.managerId ? await prisma.user.findUnique({ where: { employeeId: emp.managerId }, include: { role: { include: { permissions: { include: { permission: true } } } } } }) : null;
    if (!managerUser) return null;
    return { userId: managerUser.id, organisationId: orgId, homeOrganisationId: orgId, roleKey: managerUser.role.key, dataScope: managerUser.role.dataScope, permissions: new Set(managerUser.role.permissions.map((p) => p.permission.key)), employeeId: managerUser.employeeId, name: managerUser.name, email: managerUser.email };
  };

  let created = 0;
  for (const plan of leavePlans) {
    const start = nextWorking(addDays(today, plan.offset));
    let end = start;
    for (let d = 1; d < plan.days; d++) end = nextWorking(addDays(end, 1));
    if (end.getUTCFullYear() !== start.getUTCFullYear()) continue;
    try {
      const req = await leave.apply(hrAuth, { employeeId: idByCode[plan.code], leaveTypeId: types[plan.type].id, startDate: formatDateOnly(start), endDate: formatDateOnly(end), halfDay: false, reason: plan.reason }, undefined, actor);
      created++;
      if (plan.outcome === 'APPROVED' || plan.outcome === 'CANCELLED') {
        await leave.approve(hrAuth, req.id, undefined, actor);
        if (plan.outcome === 'CANCELLED') await leave.cancel(hrAuth, req.id, actor);
      } else if (plan.outcome === 'REJECTED') {
        await leave.reject(hrAuth, req.id, 'Team is short-staffed during this period. Please choose other dates.', actor);
      } else if (plan.outcome === 'SUPERVISOR' && types[plan.type].requiresHrApproval) {
        const mgr = await managerAuth(plan.code);
        if (mgr && mgr.permissions.has('leave.approve')) await leave.approve(mgr, req.id, undefined, actor);
      }
    } catch {
      // Overlaps or balance limits are expected occasionally with random plans; skip them.
    }
  }
  console.log(`  ${created} leave requests`);

  // ── Attendance: from 1 June until today ─────────────────────
  const attendanceStart = parseDateOnly(`${today.getUTCFullYear()}-06-01`);
  const employees = await prisma.employee.findMany({ where: { organisationId: orgId }, include: { shifts: { include: { shift: true } } } });
  const approvedLeave = await prisma.leaveRequest.findMany({ where: { organisationId: orgId, status: 'APPROVED' } });
  const leaveDays = new Set(approvedLeave.flatMap((l) => [...eachDay(l.startDate, l.endDate)].map((d) => `${l.employeeId}|${formatDateOnly(d)}`)));
  const fullCal = await loadWorkCalendar(orgId, attendanceStart, today);
  const rows: Prisma.AttendanceCreateManyInput[] = [];
  for (const e of employees) {
    const shift = e.shifts[0]?.shift ?? general;
    const rule = toShiftRule(shift);
    const startMin = Number(shift.startTime.slice(0, 2)) * 60 + Number(shift.startTime.slice(3));
    const endMin = Number(shift.endTime.slice(0, 2)) * 60 + Number(shift.endTime.slice(3));
    for (const d of eachDay(attendanceStart, today)) {
      if (d < e.joinDate || (e.exitDate && d > e.exitDate)) continue;
      if (dayKind(d, fullCal) !== 'WORKING') continue;
      const key = `${e.id}|${formatDateOnly(d)}`;
      if (leaveDays.has(key)) continue; // already marked LEAVE by the approval
      const isToday = d.getTime() === today.getTime();
      const r = rand();
      let entry: { checkIn?: string; checkOut?: string | null; status?: 'ABSENT' | 'WORK_FROM_HOME' } = {};
      if (r < 0.03) entry = { status: 'ABSENT' };
      else {
        const late = r < 0.13;
        const inMin = startMin + (late ? between(16, 55) : between(-20, 12));
        const outMin = endMin + (r > 0.9 ? between(30, 150) : between(-5, 25));
        entry = { checkIn: hhmm(inMin), checkOut: isToday ? null : hhmm(outMin), ...(r > 0.95 && e.workLocation !== 'Field' ? { status: 'WORK_FROM_HOME' as const } : {}) };
      }
      if (isToday && rand() < 0.08) continue; // a few not marked yet today
      const computed = computeAttendance({ ...entry, shift: rule });
      rows.push({
        organisationId: orgId,
        employeeId: e.id,
        date: d,
        shiftId: shift.id,
        checkIn: entry.checkIn ?? null,
        checkOut: entry.checkOut ?? null,
        source: rand() < 0.7 ? 'DEVICE' : 'MANUAL',
        ...computed,
      });
    }
  }
  await prisma.attendance.createMany({ data: rows, skipDuplicates: true });
  console.log(`  ${rows.length} attendance records`);

  // ── Payroll adjustments & runs ────────────────────────────
  const accountantAuth: AuthContext = { ...hrAuth, userId: userIds.accountant, roleKey: 'accountant', employeeId: idByCode['EMP-0007'], name: 'Kabita Poudel', email: 'accountant@example.com' };
  const payrollMonths: { year: number; month: number; final: 'PAID' | 'APPROVED' | 'DRAFT' }[] = [];
  const curMonth = today.getUTCMonth() + 1;
  for (let back = 3; back >= 1; back--) {
    const m = curMonth - back;
    if (m >= 6) payrollMonths.push({ year: today.getUTCFullYear(), month: m, final: back === 1 ? 'APPROVED' : 'PAID' });
  }
  payrollMonths.push({ year: today.getUTCFullYear(), month: curMonth, final: 'DRAFT' });

  const lastClosed = payrollMonths[payrollMonths.length - 2];
  if (lastClosed) {
    for (const code of ['EMP-0009', 'EMP-0014', 'EMP-0020']) {
      await prisma.payrollAdjustment.create({ data: { organisationId: orgId, employeeId: idByCode[code], componentId: comp.BONUS.id, year: lastClosed.year, month: lastClosed.month, amount: new Prisma.Decimal(10000), note: 'Project delivery bonus', createdById: userIds.accountant } });
    }
    await prisma.payrollAdjustment.create({ data: { organisationId: orgId, employeeId: idByCode['EMP-0025'] ?? idByCode['EMP-0010'], componentId: comp.ADVANCE.id, year: lastClosed.year, month: lastClosed.month, amount: new Prisma.Decimal(5000), note: 'Salary advance recovery (1 of 2)', createdById: userIds.accountant } });
  }
  for (const pm of payrollMonths) {
    await prisma.payrollAdjustment.create({ data: { organisationId: orgId, employeeId: idByCode['EMP-0011'], componentId: comp.LOAN.id, year: pm.year, month: pm.month, amount: new Prisma.Decimal(3000), note: 'Staff loan instalment', createdById: userIds.accountant } });
  }

  for (const pm of payrollMonths) {
    const run = await payroll.generate(accountantAuth, { year: pm.year, month: pm.month }, actor);
    if (pm.final !== 'DRAFT') {
      await payroll.review(accountantAuth, run.id, actor);
      await payroll.approve(accountantAuth, run.id, actor);
      if (pm.final === 'PAID') await payroll.markPaid(accountantAuth, run.id, actor);
    }
    console.log(`  payroll ${pm.year}-${pm.month}: ${pm.final}`);
  }

  // ── Documents ──────────────────────────────────────────────
  const docDir = path.join(env.uploadDir, 'documents');
  fs.mkdirSync(docDir, { recursive: true });
  const docPlans: [string, 'CITIZENSHIP' | 'CONTRACT' | 'APPOINTMENT_LETTER' | 'EDUCATION_CERTIFICATE' | 'PASSPORT', string, number | null][] = [
    ['EMP-0009', 'APPOINTMENT_LETTER', 'Appointment letter', null],
    ['EMP-0009', 'CITIZENSHIP', 'Citizenship certificate', null],
    ['EMP-0009', 'EDUCATION_CERTIFICATE', 'Bachelor’s degree transcript', null],
    ['EMP-0002', 'CONTRACT', 'Employment contract', 400],
    ['EMP-0004', 'PASSPORT', 'Passport', 18],
    ['EMP-0005', 'CONTRACT', 'Employment contract', 12],
    ['EMP-0010', 'CONTRACT', 'Fixed-term contract', -5],
    ['EMP-0007', 'APPOINTMENT_LETTER', 'Appointment letter', null],
  ];
  for (const [code, type, title, expiresInDays] of docPlans) {
    const emp = await prisma.employee.findUniqueOrThrow({ where: { id: idByCode[code] } });
    const file = `${crypto.randomUUID()}.pdf`;
    const size = await demoPdf(path.join(docDir, file), title, `${emp.firstName} ${emp.lastName}`);
    await prisma.employeeDocument.create({
      data: {
        organisationId: orgId,
        employeeId: emp.id,
        documentType: type,
        title,
        filePath: `documents/${file}`,
        fileName: `${title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.pdf`,
        fileSize: size,
        mimeType: 'application/pdf',
        expiryDate: expiresInDays === null ? null : addDays(today, expiresInDays),
        uploadedById: userIds.hradmin,
      },
    });
  }

  // Welcome notification for each demo user.
  for (const id of Object.values(userIds)) {
    await prisma.notification.create({ data: { organisationId: orgId, userId: id, type: 'GENERAL', title: 'Welcome to Sprasa HR', message: 'This is demo data. Change your password from your profile menu.', link: '/app/profile' } });
  }

  console.log('\nDone. Sign in at the frontend with any of these usernames:');
  for (const u of userDefs) console.log(`  ${u.username.padEnd(11)} (${u.role})`);
  console.log(`Password: the SEED_PASSWORD value (default documented in README). Change it after signing in.`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
